server {
    listen 80;

    location = / {
        return 301 /letter_to_self/;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /letter_to_self/index.html;
    }

    error_page 404 /letter_to_self/index.html;
}
